import { SportCategoryConfig } from "./types";

export const badmintonClearConfig: SportCategoryConfig = {
  sportName: "Badminton",
  movementName: "Clear",
  configKey: "badminton-clear",
  overallScoreLabel: "Clear Score",
  scores: [
    { key: "power", label: "Power", weight: 0.23 },
    { key: "control", label: "Control", weight: 0.09 },
    { key: "timing", label: "Timing", weight: 0.14 },
    { key: "technique", label: "Technique", weight: 0.41 },
    { key: "consistency", label: "Consistency", weight: 0.13 },
  ],
  metrics: [
    {
      key: "racketSpeed",
      label: "Racket Speed",
      unit: "m/s",
      icon: "speedometer",
      category: "power",
      color: "#E74C3C",
      description: "Peak racket head speed during the clear stroke",
      optimalRange: [25, 45],
    },
    {
      key: "shuttleSpeed",
      label: "Shuttle Speed",
      unit: "mph",
      icon: "flash",
      category: "ball",
      color: "#34D399",
      description: "Shuttle speed after the clear",
      optimalRange: [80, 150],
    },
    {
      key: "trajectoryHeight",
      label: "Trajectory Height",
      unit: "m",
      icon: "trending-up",
      category: "ball",
      color: "#6C5CE7",
      description: "Peak height of the shuttle trajectory",
      optimalRange: [5, 10],
    },
    {
      key: "shoulderRotation",
      label: "Shoulder Rotation",
      unit: "deg/s",
      icon: "refresh-circle",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Trunk rotation velocity during the clear",
      optimalRange: [500, 900],
    },
    {
      key: "footworkScore",
      label: "Footwork",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Quality of court movement and positioning",
      optimalRange: [65, 95],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/10",
      icon: "body",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body stability throughout the clear motion",
      optimalRange: [6.5, 9.5],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/10",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Smoothness and tempo of the clear stroke",
      optimalRange: [6.5, 9.5],
    },
  ],
};
