import { SportCategoryConfig } from "./types";

export const badmintonNetShotConfig: SportCategoryConfig = {
  sportName: "Badminton",
  movementName: "Net Shot",
  configKey: "badminton-net-shot",
  overallScoreLabel: "Net Shot Score",
  scores: [
    { key: "control", label: "Control", weight: 0.30 },
    { key: "finesse", label: "Finesse", weight: 0.25 },
    { key: "footwork", label: "Footwork", weight: 0.20 },
    { key: "consistency", label: "Consistency", weight: 0.15 },
    { key: "timing", label: "Timing", weight: 0.10 },
  ],
  metrics: [
    {
      key: "racketControl",
      label: "Racket Control",
      unit: "/100",
      icon: "hand-right",
      category: "technique",
      color: "#FBBF24",
      description: "Precision of racket face control at the net",
      optimalRange: [70, 98],
    },
    {
      key: "wristFinesse",
      label: "Wrist Finesse",
      unit: "/100",
      icon: "finger-print",
      category: "technique",
      color: "#FBBF24",
      description: "Delicacy and precision of wrist movements",
      optimalRange: [70, 98],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/100",
      icon: "body",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body stability during the net shot",
      optimalRange: [65, 95],
    },
    {
      key: "footworkScore",
      label: "Footwork",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Quality of movement to the net",
      optimalRange: [65, 95],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/100",
      icon: "ribbon",
      category: "consistency",
      color: "#6C5CE7",
      description: "Repeatability of net shot technique",
      optimalRange: [70, 98],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Fluidity and timing of the net shot motion",
      optimalRange: [65, 95],
    },
  ],
};
