import { SportCategoryConfig } from "./types";

export const badmintonServeConfig: SportCategoryConfig = {
  sportName: "Badminton",
  movementName: "Serve",
  configKey: "badminton-serve",
  overallScoreLabel: "Serve Score",
  scores: [
    { key: "accuracy", label: "Accuracy", weight: 0.30 },
    { key: "technique", label: "Technique", weight: 0.25 },
    { key: "consistency", label: "Consistency", weight: 0.25 },
    { key: "timing", label: "Timing", weight: 0.20 },
  ],
  metrics: [
    {
      key: "racketAngle",
      label: "Racket Angle",
      unit: "deg",
      icon: "analytics",
      category: "technique",
      color: "#FBBF24",
      description: "Racket face angle at shuttle contact",
      optimalRange: [15, 40],
    },
    {
      key: "shuttleSpeed",
      label: "Shuttle Speed",
      unit: "mph",
      icon: "flash",
      category: "ball",
      color: "#34D399",
      description: "Shuttle speed after the serve",
      optimalRange: [30, 100],
    },
    {
      key: "placementScore",
      label: "Placement",
      unit: "/100",
      icon: "locate",
      category: "ball",
      color: "#34D399",
      description: "Accuracy of serve placement in the target zone",
      optimalRange: [70, 98],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/100",
      icon: "ribbon",
      category: "consistency",
      color: "#6C5CE7",
      description: "Repeatability of serve technique and placement",
      optimalRange: [70, 98],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Smoothness and timing of the serve motion",
      optimalRange: [65, 95],
    },
  ],
};
