import { SportCategoryConfig } from "./types";

export const badmintonSmashConfig: SportCategoryConfig = {
  sportName: "Badminton",
  movementName: "Smash",
  configKey: "badminton-smash",
  overallScoreLabel: "Smash Score",
  scores: [
    { key: "power", label: "Power", weight: 0.41 },
    { key: "control", label: "Control", weight: 0.09 },
    { key: "timing", label: "Timing", weight: 0.18 },
    { key: "technique", label: "Technique", weight: 0.23 },
    { key: "consistency", label: "Consistency", weight: 0.09 },
  ],
  metrics: [
    {
      key: "racketSpeed",
      label: "Racket Speed",
      unit: "m/s",
      icon: "speedometer",
      category: "power",
      color: "#E74C3C",
      description: "Peak racket head speed during the smash",
      optimalRange: [35, 60],
    },
    {
      key: "shuttleSpeed",
      label: "Shuttle Speed",
      unit: "mph",
      icon: "flash",
      category: "ball",
      color: "#34D399",
      description: "Shuttle speed after the smash",
      optimalRange: [150, 300],
    },
    {
      key: "jumpHeight",
      label: "Jump Height",
      unit: "m",
      icon: "arrow-up-circle",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Height gained during the jump smash",
      optimalRange: [0.2, 0.6],
    },
    {
      key: "contactHeight",
      label: "Contact Height",
      unit: "m",
      icon: "resize",
      category: "technique",
      color: "#FBBF24",
      description: "Height of racket at shuttle contact",
      optimalRange: [2.5, 3.2],
    },
    {
      key: "wristSnap",
      label: "Wrist Snap",
      unit: "deg/s",
      icon: "hand-right",
      category: "technique",
      color: "#FBBF24",
      description: "Wrist snap speed at contact for maximum power",
      optimalRange: [400, 800],
    },
    {
      key: "bodyRotation",
      label: "Body Rotation",
      unit: "deg/s",
      icon: "refresh-circle",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Full body rotation velocity during the smash",
      optimalRange: [500, 1000],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/10",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Smoothness and timing of the smash motion",
      optimalRange: [6.5, 9.5],
    },
  ],
};
