import { SportCategoryConfig } from "./types";

export const badmintonDropConfig: SportCategoryConfig = {
  sportName: "Badminton",
  movementName: "Drop Shot",
  configKey: "badminton-drop",
  overallScoreLabel: "Drop Shot Score",
  scores: [
    { key: "power", label: "Power", weight: 0.11 },
    { key: "control", label: "Control", weight: 0.49 },
    { key: "timing", label: "Timing", weight: 0.09 },
    { key: "technique", label: "Technique", weight: 0.18 },
    { key: "consistency", label: "Consistency", weight: 0.13 },
  ],
  metrics: [
    {
      key: "touchScore",
      label: "Touch",
      unit: "/100",
      icon: "finger-print",
      category: "technique",
      color: "#FBBF24",
      description: "Softness and precision of the drop shot",
      optimalRange: [70, 98],
    },
    {
      key: "deceptionScore",
      label: "Deception",
      unit: "/100",
      icon: "eye-off",
      category: "technique",
      color: "#FBBF24",
      description: "How well the shot disguises intent",
      optimalRange: [65, 95],
    },
    {
      key: "netClearance",
      label: "Net Clearance",
      unit: "cm",
      icon: "resize",
      category: "ball",
      color: "#34D399",
      description: "Height above the net the shuttle passes",
      optimalRange: [2, 15],
    },
    {
      key: "racketAngle",
      label: "Racket Angle",
      unit: "deg",
      icon: "analytics",
      category: "technique",
      color: "#FBBF24",
      description: "Racket face angle at contact",
      optimalRange: [20, 45],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/100",
      icon: "ribbon",
      category: "consistency",
      color: "#6C5CE7",
      description: "Repeatability of drop shot placement",
      optimalRange: [70, 98],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Fluidity and timing of the drop shot motion",
      optimalRange: [65, 95],
    },
  ],
};
