import { SportCategoryConfig } from "./types";

export const golfChipConfig: SportCategoryConfig = {
  sportName: "Golf",
  movementName: "Chip",
  configKey: "golf-chip",
  overallScoreLabel: "Chip Score",
  scores: [
    { key: "power", label: "Power", weight: 0.10 },
    { key: "control", label: "Control", weight: 0.33 },
    { key: "timing", label: "Timing", weight: 0.08 },
    { key: "technique", label: "Technique", weight: 0.29 },
    { key: "consistency", label: "Consistency", weight: 0.20 },
  ],
  metrics: [
    {
      key: "wristHinge",
      label: "Wrist Hinge",
      unit: "deg",
      icon: "hand-right",
      category: "technique",
      color: "#FBBF24",
      description: "Amount of wrist hinge — minimal for chip shots",
      optimalRange: [5, 20],
    },
    {
      key: "armPendulum",
      label: "Arm Pendulum",
      unit: "/100",
      icon: "swap-vertical",
      category: "technique",
      color: "#FBBF24",
      description: "Arms and club moving as one unit, pendulum-like",
      optimalRange: [75, 98],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/10",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Weight distribution — should favor front foot",
      optimalRange: [7, 9.8],
    },
    {
      key: "headStability",
      label: "Head Stability",
      unit: "/100",
      icon: "locate",
      category: "technique",
      color: "#FBBF24",
      description: "Head must stay very still during chip shots",
      optimalRange: [80, 98],
    },
    {
      key: "strokeLength",
      label: "Stroke Length",
      unit: "/100",
      icon: "resize",
      category: "technique",
      color: "#6C5CE7",
      description: "Appropriate stroke length for distance control",
      optimalRange: [60, 90],
    },
    {
      key: "contactQuality",
      label: "Contact Quality",
      unit: "/100",
      icon: "radio-button-on",
      category: "technique",
      color: "#6C5CE7",
      description: "Clean ball-first contact quality",
      optimalRange: [70, 98],
    },
    {
      key: "followThroughRatio",
      label: "Follow-through",
      unit: "/100",
      icon: "arrow-forward-circle",
      category: "timing",
      color: "#60A5FA",
      description: "Follow-through length relative to backswing",
      optimalRange: [70, 95],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/10",
      icon: "musical-notes",
      category: "consistency",
      color: "#6C5CE7",
      description: "Smoothness of the chipping motion",
      optimalRange: [7, 9.5],
    },
  ],
};
