import { SportCategoryConfig } from "./types";

export const golfFullSwingConfig: SportCategoryConfig = {
  sportName: "Golf",
  movementName: "Full Swing",
  configKey: "golf-full-swing",
  overallScoreLabel: "Full Swing Score",
  scores: [
    { key: "power", label: "Power", weight: 0.25 },
    { key: "control", label: "Control", weight: 0.15 },
    { key: "timing", label: "Timing", weight: 0.15 },
    { key: "technique", label: "Technique", weight: 0.25 },
    { key: "consistency", label: "Consistency", weight: 0.20 },
  ],
  metrics: [
    {
      key: "clubHeadSpeed",
      label: "Club Head Speed",
      unit: "mph",
      icon: "speedometer",
      category: "power",
      color: "#6C5CE7",
      description: "Club head speed at impact",
      optimalRange: [80, 110],
    },
    {
      key: "hipRotation",
      label: "Hip Rotation",
      unit: "deg",
      icon: "refresh-circle",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Hip rotation from address through impact",
      optimalRange: [35, 55],
    },
    {
      key: "shoulderRotation",
      label: "Shoulder Turn",
      unit: "deg",
      icon: "body",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Full torso rotation at top of swing",
      optimalRange: [75, 100],
    },
    {
      key: "xFactor",
      label: "X-Factor",
      unit: "deg",
      icon: "analytics",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Shoulder-hip separation at top of backswing",
      optimalRange: [30, 50],
    },
    {
      key: "spineAngle",
      label: "Spine Angle",
      unit: "deg",
      icon: "trending-down",
      category: "technique",
      color: "#FBBF24",
      description: "Spine tilt consistency from address to follow-through",
      optimalRange: [25, 40],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Weight distribution and stability",
      optimalRange: [70, 98],
    },
    {
      key: "tempoRatio",
      label: "Tempo Ratio",
      unit: ":1",
      icon: "timer",
      category: "timing",
      color: "#6C5CE7",
      description: "Backswing-to-downswing timing ratio",
      optimalRange: [2.5, 3.5],
    },
    {
      key: "backswingDuration",
      label: "Backswing",
      unit: "s",
      icon: "arrow-back-circle",
      category: "timing",
      color: "#60A5FA",
      description: "Backswing phase duration",
      optimalRange: [0.7, 1.2],
    },
    {
      key: "headStability",
      label: "Head Stability",
      unit: "/100",
      icon: "locate",
      category: "technique",
      color: "#FBBF24",
      description: "Head position steadiness",
      optimalRange: [70, 98],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "consistency",
      color: "#6C5CE7",
      description: "Overall swing rhythm and flow",
      optimalRange: [65, 95],
    },
  ],
};
