import { SportCategoryConfig } from "./types";

export const golfDriveConfig: SportCategoryConfig = {
  sportName: "Golf",
  movementName: "Drive",
  configKey: "golf-drive",
  overallScoreLabel: "Drive Score",
  scores: [
    { key: "power", label: "Power", weight: 0.30 },
    { key: "control", label: "Control", weight: 0.10 },
    { key: "timing", label: "Timing", weight: 0.15 },
    { key: "technique", label: "Technique", weight: 0.25 },
    { key: "consistency", label: "Consistency", weight: 0.20 },
  ],
  metrics: [
    {
      key: "clubHeadSpeed",
      label: "Club Head Speed",
      unit: "mph",
      icon: "speedometer",
      category: "power",
      color: "#6C5CE7",
      description: "Estimated speed of the club head at impact",
      optimalRange: [85, 115],
    },
    {
      key: "hipRotation",
      label: "Hip Rotation",
      unit: "deg",
      icon: "refresh-circle",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Hip rotation angle from address to impact",
      optimalRange: [35, 55],
    },
    {
      key: "shoulderRotation",
      label: "Shoulder Turn",
      unit: "deg",
      icon: "body",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Shoulder rotation angle at top of backswing",
      optimalRange: [75, 100],
    },
    {
      key: "xFactor",
      label: "X-Factor",
      unit: "deg",
      icon: "analytics",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Difference between shoulder and hip rotation at top of backswing",
      optimalRange: [30, 50],
    },
    {
      key: "spineAngle",
      label: "Spine Angle",
      unit: "deg",
      icon: "trending-down",
      category: "technique",
      color: "#FBBF24",
      description: "Forward tilt angle of the spine at address and impact",
      optimalRange: [25, 40],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Weight distribution and stability throughout the swing",
      optimalRange: [70, 98],
    },
    {
      key: "tempoRatio",
      label: "Tempo Ratio",
      unit: ":1",
      icon: "timer",
      category: "timing",
      color: "#6C5CE7",
      description: "Backswing-to-downswing time ratio (ideal ~3:1)",
      optimalRange: [2.5, 3.5],
    },
    {
      key: "backswingDuration",
      label: "Backswing",
      unit: "s",
      icon: "arrow-back-circle",
      category: "timing",
      color: "#60A5FA",
      description: "Duration of the backswing phase",
      optimalRange: [0.7, 1.2],
    },
    {
      key: "downswingDuration",
      label: "Downswing",
      unit: "s",
      icon: "arrow-forward-circle",
      category: "timing",
      color: "#6C5CE7",
      description: "Duration of the downswing to impact",
      optimalRange: [0.2, 0.4],
    },
    {
      key: "followThroughDuration",
      label: "Follow-through",
      unit: "s",
      icon: "arrow-up-circle",
      category: "timing",
      color: "#60A5FA",
      description: "Duration of post-impact follow-through",
      optimalRange: [0.5, 1.0],
    },
    {
      key: "headStability",
      label: "Head Stability",
      unit: "/100",
      icon: "locate",
      category: "technique",
      color: "#FBBF24",
      description: "Head position steadiness throughout the swing",
      optimalRange: [70, 98],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "consistency",
      color: "#6C5CE7",
      description: "Overall smoothness and flow of the swing",
      optimalRange: [65, 95],
    },
  ],
};
