import { SportCategoryConfig } from "./types";

export const golfPuttConfig: SportCategoryConfig = {
  sportName: "Golf",
  movementName: "Putt",
  configKey: "golf-putt",
  overallScoreLabel: "Putting Score",
  scores: [
    { key: "technique", label: "Technique", weight: 0.30 },
    { key: "consistency", label: "Consistency", weight: 0.30 },
    { key: "alignment", label: "Alignment", weight: 0.25 },
    { key: "touch", label: "Touch", weight: 0.15 },
  ],
  metrics: [
    {
      key: "pendulumScore",
      label: "Pendulum",
      unit: "/100",
      icon: "swap-vertical",
      category: "technique",
      color: "#FBBF24",
      description: "Shoulder-driven pendulum motion quality",
      optimalRange: [75, 98],
    },
    {
      key: "headStability",
      label: "Head Stability",
      unit: "/100",
      icon: "locate",
      category: "technique",
      color: "#FBBF24",
      description: "Head must remain perfectly still during putting",
      optimalRange: [85, 98],
    },
    {
      key: "eyeLine",
      label: "Eye Line",
      unit: "/100",
      icon: "eye",
      category: "technique",
      color: "#6C5CE7",
      description: "Eyes positioned directly over the ball",
      optimalRange: [75, 98],
    },
    {
      key: "strokeLength",
      label: "Stroke Length",
      unit: "/100",
      icon: "resize",
      category: "technique",
      color: "#6C5CE7",
      description: "Backswing and follow-through length symmetry",
      optimalRange: [70, 95],
    },
    {
      key: "wristStability",
      label: "Wrist Stability",
      unit: "/100",
      icon: "lock-closed",
      category: "technique",
      color: "#FBBF24",
      description: "Wrist should not break during the putting stroke",
      optimalRange: [80, 98],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body stability — no swaying or weight shift",
      optimalRange: [80, 98],
    },
    {
      key: "tempoRatio",
      label: "Tempo",
      unit: ":1",
      icon: "timer",
      category: "timing",
      color: "#6C5CE7",
      description: "Backswing-to-forward ratio (ideal ~1:1 for putting)",
      optimalRange: [0.8, 1.2],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "consistency",
      color: "#6C5CE7",
      description: "Smoothness and consistency of stroke tempo",
      optimalRange: [75, 98],
    },
  ],
};
