import { SportCategoryConfig } from "./types";

export const golfIronConfig: SportCategoryConfig = {
  sportName: "Golf",
  movementName: "Iron Shot",
  configKey: "golf-iron",
  overallScoreLabel: "Iron Shot Score",
  scores: [
    { key: "technique", label: "Technique", weight: 0.30 },
    { key: "accuracy", label: "Accuracy", weight: 0.25 },
    { key: "consistency", label: "Consistency", weight: 0.20 },
    { key: "power", label: "Power", weight: 0.15 },
    { key: "balance", label: "Balance", weight: 0.10 },
  ],
  metrics: [
    {
      key: "clubHeadSpeed",
      label: "Club Head Speed",
      unit: "mph",
      icon: "speedometer",
      category: "power",
      color: "#6C5CE7",
      description: "Club head speed at impact — varies by iron",
      optimalRange: [70, 95],
    },
    {
      key: "hipRotation",
      label: "Hip Rotation",
      unit: "deg",
      icon: "refresh-circle",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Hip rotation for controlled iron strikes",
      optimalRange: [30, 50],
    },
    {
      key: "shoulderRotation",
      label: "Shoulder Turn",
      unit: "deg",
      icon: "body",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Shoulder rotation at top of backswing",
      optimalRange: [70, 95],
    },
    {
      key: "spineAngle",
      label: "Spine Angle",
      unit: "deg",
      icon: "trending-down",
      category: "technique",
      color: "#FBBF24",
      description: "Spine tilt consistency through the swing",
      optimalRange: [28, 42],
    },
    {
      key: "divotAngle",
      label: "Divot Angle",
      unit: "deg",
      icon: "push",
      category: "technique",
      color: "#FBBF24",
      description: "Angle of attack — descending blow for irons",
      optimalRange: [-5, -1],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Weight transfer and stability",
      optimalRange: [70, 98],
    },
    {
      key: "tempoRatio",
      label: "Tempo Ratio",
      unit: ":1",
      icon: "timer",
      category: "timing",
      color: "#6C5CE7",
      description: "Backswing-to-downswing time ratio",
      optimalRange: [2.5, 3.5],
    },
    {
      key: "backswingDuration",
      label: "Backswing",
      unit: "s",
      icon: "arrow-back-circle",
      category: "timing",
      color: "#60A5FA",
      description: "Backswing duration",
      optimalRange: [0.6, 1.1],
    },
    {
      key: "headStability",
      label: "Head Stability",
      unit: "/100",
      icon: "locate",
      category: "technique",
      color: "#FBBF24",
      description: "Head steadiness during the iron swing",
      optimalRange: [75, 98],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "consistency",
      color: "#6C5CE7",
      description: "Swing rhythm consistency",
      optimalRange: [65, 95],
    },
  ],
};
