import { SportCategoryConfig } from "./types";

export const paddleBandejaConfig: SportCategoryConfig = {
  sportName: "Paddle",
  movementName: "Bandeja",
  configKey: "paddle-bandeja",
  overallScoreLabel: "Bandeja Score",
  scores: [
    { key: "power", label: "Power", weight: 0.11 },
    { key: "control", label: "Control", weight: 0.27 },
    { key: "timing", label: "Timing", weight: 0.18 },
    { key: "technique", label: "Technique", weight: 0.22 },
    { key: "consistency", label: "Consistency", weight: 0.22 },
  ],
  metrics: [
    {
      key: "paddleAngle",
      label: "Paddle Angle",
      unit: "deg",
      icon: "analytics",
      category: "technique",
      color: "#FBBF24",
      description: "Angle of paddle face for the defensive slice",
      optimalRange: [20, 50],
    },
    {
      key: "ballSpeed",
      label: "Ball Speed",
      unit: "mph",
      icon: "flash",
      category: "ball",
      color: "#34D399",
      description: "Ball speed after the bandeja contact",
      optimalRange: [25, 55],
    },
    {
      key: "wristControl",
      label: "Wrist Control",
      unit: "/100",
      icon: "hand-right",
      category: "technique",
      color: "#FBBF24",
      description: "Wrist stability and control during the slice motion",
      optimalRange: [70, 98],
    },
    {
      key: "contactHeight",
      label: "Contact Height",
      unit: "m",
      icon: "resize",
      category: "technique",
      color: "#FBBF24",
      description: "Height of paddle at ball contact during bandeja",
      optimalRange: [1.8, 2.8],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body stability during the defensive overhead",
      optimalRange: [70, 98],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/100",
      icon: "ribbon",
      category: "consistency",
      color: "#6C5CE7",
      description: "Repeatability of bandeja technique",
      optimalRange: [70, 98],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Fluidity and timing of the bandeja motion",
      optimalRange: [65, 95],
    },
  ],
};
