import { SportCategoryConfig } from "./types";

export const paddleForehandConfig: SportCategoryConfig = {
  sportName: "Paddle",
  movementName: "Forehand",
  configKey: "paddle-forehand",
  overallScoreLabel: "Forehand Score",
  scores: [
    { key: "power", label: "Power", weight: 0.18 },
    { key: "control", label: "Control", weight: 0.09 },
    { key: "timing", label: "Timing", weight: 0.18 },
    { key: "technique", label: "Technique", weight: 0.41 },
    { key: "consistency", label: "Consistency", weight: 0.14 },
  ],
  metrics: [
    {
      key: "wristSpeed",
      label: "Wrist Speed",
      unit: "m/s",
      icon: "speedometer",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Peak wrist velocity during the forehand swing",
      optimalRange: [18, 32],
    },
    {
      key: "elbowAngle",
      label: "Elbow Angle",
      unit: "deg",
      icon: "body",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Average elbow joint angle during the stroke",
      optimalRange: [110, 150],
    },
    {
      key: "shoulderRotation",
      label: "Shoulder Rotation",
      unit: "deg/s",
      icon: "refresh-circle",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Angular velocity of torso rotation during the swing",
      optimalRange: [400, 800],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Hip-to-ankle alignment stability throughout the stroke",
      optimalRange: [70, 98],
    },
    {
      key: "ballSpeed",
      label: "Ball Speed",
      unit: "mph",
      icon: "flash",
      category: "ball",
      color: "#34D399",
      description: "Estimated ball speed after contact",
      optimalRange: [40, 80],
    },
    {
      key: "wallPlayScore",
      label: "Wall Play",
      unit: "/100",
      icon: "grid",
      category: "technique",
      color: "#FBBF24",
      description: "Quality of wall utilization and rebound anticipation",
      optimalRange: [60, 95],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/100",
      icon: "ribbon",
      category: "consistency",
      color: "#6C5CE7",
      description: "Variance in technique across repeated strokes",
      optimalRange: [70, 98],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Smoothness and timing flow throughout the swing",
      optimalRange: [65, 95],
    },
    {
      key: "contactHeight",
      label: "Contact Height",
      unit: "m",
      icon: "resize",
      category: "technique",
      color: "#FBBF24",
      description: "Height of contact point relative to ground",
      optimalRange: [0.7, 1.10],
    },
  ],
};
