import { SportCategoryConfig } from "./types";

export const paddleSmashConfig: SportCategoryConfig = {
  sportName: "Paddle",
  movementName: "Smash",
  configKey: "paddle-smash",
  overallScoreLabel: "Smash Score",
  scores: [
    { key: "power", label: "Power", weight: 0.47 },
    { key: "control", label: "Control", weight: 0.09 },
    { key: "timing", label: "Timing", weight: 0.17 },
    { key: "technique", label: "Technique", weight: 0.21 },
    { key: "consistency", label: "Consistency", weight: 0.06 },
  ],
  metrics: [
    {
      key: "wristSpeed",
      label: "Wrist Speed",
      unit: "m/s",
      icon: "speedometer",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Peak wrist velocity during the overhead smash",
      optimalRange: [22, 38],
    },
    {
      key: "shoulderRotation",
      label: "Shoulder Rotation",
      unit: "deg/s",
      icon: "refresh-circle",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Angular velocity of torso rotation during the smash",
      optimalRange: [500, 900],
    },
    {
      key: "jumpHeight",
      label: "Jump Height",
      unit: "m",
      icon: "arrow-up-circle",
      category: "power",
      color: "#EF4444",
      description: "Vertical jump height during the smash",
      optimalRange: [0.1, 0.5],
    },
    {
      key: "ballSpeed",
      label: "Ball Speed",
      unit: "mph",
      icon: "flash",
      category: "ball",
      color: "#34D399",
      description: "Ball speed after the overhead smash",
      optimalRange: [50, 90],
    },
    {
      key: "contactHeight",
      label: "Contact Height",
      unit: "m",
      icon: "resize",
      category: "technique",
      color: "#FBBF24",
      description: "Height of paddle at ball contact during smash",
      optimalRange: [2.0, 3.0],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/10",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body stability during and after the smash",
      optimalRange: [6.5, 9.5],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/10",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Fluidity and timing of the smash motion",
      optimalRange: [6, 9.2],
    },
  ],
};
