import { SportCategoryConfig } from "./types";

export const paddleServeConfig: SportCategoryConfig = {
  sportName: "Paddle",
  movementName: "Serve",
  configKey: "paddle-serve",
  overallScoreLabel: "Serve Score",
  scores: [
    { key: "technique", label: "Technique", weight: 0.30 },
    { key: "placement", label: "Placement", weight: 0.25 },
    { key: "consistency", label: "Consistency", weight: 0.25 },
    { key: "timing", label: "Timing", weight: 0.20 },
  ],
  metrics: [
    {
      key: "paddleAngle",
      label: "Paddle Angle",
      unit: "deg",
      icon: "analytics",
      category: "technique",
      color: "#FBBF24",
      description: "Angle of paddle face at contact for slice or flat serve",
      optimalRange: [15, 45],
    },
    {
      key: "ballSpeed",
      label: "Ball Speed",
      unit: "mph",
      icon: "flash",
      category: "ball",
      color: "#34D399",
      description: "Ball speed after serve contact",
      optimalRange: [30, 60],
    },
    {
      key: "placementScore",
      label: "Placement",
      unit: "/100",
      icon: "locate",
      category: "technique",
      color: "#FBBF24",
      description: "Accuracy of serve placement in the service box",
      optimalRange: [65, 98],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/100",
      icon: "ribbon",
      category: "consistency",
      color: "#6C5CE7",
      description: "Repeatability of serve technique across attempts",
      optimalRange: [70, 98],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body stability during the underhand serve motion",
      optimalRange: [70, 98],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Smoothness and timing of the serve motion",
      optimalRange: [65, 95],
    },
  ],
};
