import { SportCategoryConfig } from "./types";

export const pickleballDriveConfig: SportCategoryConfig = {
  sportName: "Pickleball",
  movementName: "Drive",
  configKey: "pickleball-drive",
  overallScoreLabel: "Drive Score",
  scores: [
    { key: "power", label: "Power", weight: 0.25 },
    { key: "technique", label: "Technique", weight: 0.20 },
    { key: "trajectory", label: "Trajectory", weight: 0.15 },
    { key: "stability", label: "Stability", weight: 0.15 },
    { key: "consistency", label: "Consistency", weight: 0.15 },
    { key: "rhythm", label: "Rhythm", weight: 0.10 },
  ],
  metrics: [
    {
      key: "paddleSpeed",
      label: "Paddle Speed",
      unit: "m/s",
      icon: "speedometer",
      category: "power",
      color: "#EF4444",
      description: "Peak paddle velocity during the drive swing",
      optimalRange: [15, 30],
    },
    {
      key: "bodyRotation",
      label: "Body Rotation",
      unit: "deg/s",
      icon: "refresh-circle",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Angular velocity of trunk rotation generating drive power",
      optimalRange: [300, 700],
    },
    {
      key: "ballSpeed",
      label: "Ball Speed",
      unit: "mph",
      icon: "flash",
      category: "ball",
      color: "#34D399",
      description: "Estimated ball speed off the paddle face",
      optimalRange: [35, 65],
    },
    {
      key: "trajectoryAngle",
      label: "Trajectory",
      unit: "deg",
      icon: "trending-up",
      category: "ball",
      color: "#34D399",
      description: "Launch angle of the drive — flat and aggressive is ideal",
      optimalRange: [2, 12],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body stability during the aggressive drive motion",
      optimalRange: [65, 95],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/100",
      icon: "ribbon",
      category: "consistency",
      color: "#6C5CE7",
      description: "Repeatability of drive technique across multiple shots",
      optimalRange: [65, 95],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Smoothness and tempo of the drive motion",
      optimalRange: [60, 90],
    },
  ],
};
