import { SportCategoryConfig } from "./types";

export const pickleballDinkConfig: SportCategoryConfig = {
  sportName: "Pickleball",
  movementName: "Dink",
  configKey: "pickleball-dink",
  overallScoreLabel: "Dink Score",
  scores: [
    { key: "touch", label: "Soft Touch", weight: 0.25 },
    { key: "technique", label: "Technique", weight: 0.20 },
    { key: "arc", label: "Arc Control", weight: 0.15 },
    { key: "stability", label: "Stability", weight: 0.15 },
    { key: "consistency", label: "Consistency", weight: 0.15 },
    { key: "rhythm", label: "Rhythm", weight: 0.10 },
  ],
  metrics: [
    {
      key: "paddleAngle",
      label: "Paddle Angle",
      unit: "deg",
      icon: "analytics",
      category: "technique",
      color: "#FBBF24",
      description: "Paddle face angle at contact — open face for controlled dinks",
      optimalRange: [25, 50],
    },
    {
      key: "softTouch",
      label: "Soft Touch",
      unit: "/100",
      icon: "hand-right",
      category: "technique",
      color: "#6C5CE7",
      description: "Ability to absorb pace and keep the ball low over the net",
      optimalRange: [70, 98],
    },
    {
      key: "wristStability",
      label: "Wrist Stability",
      unit: "/100",
      icon: "lock-closed",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Wrist firmness during contact for precise placement",
      optimalRange: [75, 98],
    },
    {
      key: "arcHeight",
      label: "Arc Height",
      unit: "m",
      icon: "trending-up",
      category: "ball",
      color: "#34D399",
      description: "Peak height of the ball above the net during the dink",
      optimalRange: [0.05, 0.30],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body stability during the dink motion",
      optimalRange: [70, 98],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/100",
      icon: "ribbon",
      category: "consistency",
      color: "#6C5CE7",
      description: "Repeatability of dink technique across multiple shots",
      optimalRange: [70, 98],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Smoothness and tempo of the dink motion",
      optimalRange: [65, 95],
    },
  ],
};
