import { SportCategoryConfig } from "./types";

export const pickleballDriveConfig: SportCategoryConfig = {
  sportName: "Pickleball",
  movementName: "Drive",
  configKey: "pickleball-drive",
  overallScoreLabel: "Drive Score",
  scores: [
    { key: "power", label: "Power", weight: 0.25 },
    { key: "control", label: "Control", weight: 0.15 },
    { key: "timing", label: "Timing", weight: 0.10 },
    { key: "technique", label: "Technique", weight: 0.35 },
    { key: "consistency", label: "Consistency", weight: 0.15 },
  ],
  metrics: [
    {
      key: "paddleSpeed",
      label: "Paddle Speed",
      unit: "m/s",
      icon: "speedometer",
      category: "power",
      color: "#EF4444",
      description: "Peak paddle velocity during the drive swing",
      optimalRange: [15, 30],
    },
    {
      key: "bodyRotation",
      label: "Body Rotation",
      unit: "deg/s",
      icon: "refresh-circle",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Angular velocity of trunk rotation generating drive power",
      optimalRange: [300, 700],
    },
    {
      key: "ballSpeed",
      label: "Ball Speed",
      unit: "mph",
      icon: "flash",
      category: "ball",
      color: "#34D399",
      description: "Estimated ball speed off the paddle face",
      optimalRange: [35, 65],
    },
    {
      key: "trajectoryAngle",
      label: "Trajectory",
      unit: "deg",
      icon: "trending-up",
      category: "ball",
      color: "#34D399",
      description: "Launch angle of the drive — flat and aggressive is ideal",
      optimalRange: [2, 12],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/10",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body stability during the aggressive drive motion",
      optimalRange: [6.5, 9.5],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/10",
      icon: "ribbon",
      category: "consistency",
      color: "#6C5CE7",
      description: "Repeatability of drive technique across multiple shots",
      optimalRange: [6.5, 9.5],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/10",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Smoothness and tempo of the drive motion",
      optimalRange: [6, 9],
    },
  ],
};
