import { SportCategoryConfig } from "./types";

export const pickleballVolleyConfig: SportCategoryConfig = {
  sportName: "Pickleball",
  movementName: "Volley",
  configKey: "pickleball-volley",
  overallScoreLabel: "Volley Score",
  scores: [
    { key: "reflexes", label: "Reflexes", weight: 0.25 },
    { key: "technique", label: "Technique", weight: 0.20 },
    { key: "stability", label: "Stability", weight: 0.15 },
    { key: "power", label: "Power", weight: 0.15 },
    { key: "consistency", label: "Consistency", weight: 0.15 },
    { key: "rhythm", label: "Rhythm", weight: 0.10 },
  ],
  metrics: [
    {
      key: "reactionSpeed",
      label: "Reaction Speed",
      unit: "ms",
      icon: "flash",
      category: "timing",
      color: "#6C5CE7",
      description: "Time from opponent's contact to paddle movement initiation",
      optimalRange: [120, 300],
    },
    {
      key: "paddlePrep",
      label: "Paddle Prep",
      unit: "/100",
      icon: "hand-right",
      category: "technique",
      color: "#FBBF24",
      description: "Readiness and position of paddle before the volley",
      optimalRange: [70, 98],
    },
    {
      key: "wristFirmness",
      label: "Wrist Firmness",
      unit: "/100",
      icon: "lock-closed",
      category: "technique",
      color: "#FBBF24",
      description: "Wrist stability at contact for controlled volleys",
      optimalRange: [75, 98],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body stability during quick volley exchanges",
      optimalRange: [65, 95],
    },
    {
      key: "ballSpeed",
      label: "Ball Speed",
      unit: "mph",
      icon: "speedometer",
      category: "ball",
      color: "#34D399",
      description: "Ball speed after the volley contact",
      optimalRange: [20, 50],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/100",
      icon: "ribbon",
      category: "consistency",
      color: "#6C5CE7",
      description: "Repeatability of volley technique across exchanges",
      optimalRange: [65, 95],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Fluidity and tempo of volley exchanges",
      optimalRange: [60, 90],
    },
  ],
};
