import { SportCategoryConfig } from "./types";

export const pickleballThirdShotDropConfig: SportCategoryConfig = {
  sportName: "Pickleball",
  movementName: "Third Shot Drop",
  configKey: "pickleball-third-shot-drop",
  overallScoreLabel: "Third Shot Drop Score",
  scores: [
    { key: "touch", label: "Soft Touch", weight: 0.25 },
    { key: "arc", label: "Arc Control", weight: 0.20 },
    { key: "technique", label: "Technique", weight: 0.20 },
    { key: "consistency", label: "Consistency", weight: 0.15 },
    { key: "stability", label: "Stability", weight: 0.10 },
    { key: "rhythm", label: "Rhythm", weight: 0.10 },
  ],
  metrics: [
    {
      key: "arcHeight",
      label: "Arc Height",
      unit: "m",
      icon: "trending-up",
      category: "ball",
      color: "#34D399",
      description: "Peak height of the drop shot — should clear net but land softly",
      optimalRange: [0.10, 0.40],
    },
    {
      key: "softTouch",
      label: "Soft Touch",
      unit: "/100",
      icon: "hand-right",
      category: "technique",
      color: "#6C5CE7",
      description: "Ability to decelerate the paddle for a soft landing",
      optimalRange: [70, 98],
    },
    {
      key: "paddleAngle",
      label: "Paddle Angle",
      unit: "deg",
      icon: "analytics",
      category: "technique",
      color: "#FBBF24",
      description: "Paddle face angle for proper drop shot trajectory",
      optimalRange: [30, 55],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/100",
      icon: "ribbon",
      category: "consistency",
      color: "#6C5CE7",
      description: "Repeatability of third shot drop execution",
      optimalRange: [65, 95],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body stability during the transition drop shot",
      optimalRange: [70, 98],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Smoothness and timing of the drop shot motion",
      optimalRange: [65, 95],
    },
  ],
};
