import { SportCategoryConfig } from "./types";

export const pickleballServeConfig: SportCategoryConfig = {
  sportName: "Pickleball",
  movementName: "Serve",
  configKey: "pickleball-serve",
  overallScoreLabel: "Serve Score",
  scores: [
    { key: "power", label: "Power", weight: 0.15 },
    { key: "control", label: "Control", weight: 0.35 },
    { key: "timing", label: "Timing", weight: 0.10 },
    { key: "technique", label: "Technique", weight: 0.25 },
    { key: "consistency", label: "Consistency", weight: 0.15 },
  ],
  metrics: [
    {
      key: "paddleAngle",
      label: "Paddle Angle",
      unit: "deg",
      icon: "analytics",
      category: "technique",
      color: "#FBBF24",
      description: "Paddle face angle during the underhand serve motion",
      optimalRange: [20, 45],
    },
    {
      key: "tossConsistency",
      label: "Toss Consistency",
      unit: "/100",
      icon: "arrow-up-circle",
      category: "technique",
      color: "#FBBF24",
      description: "Consistency of ball toss height and placement",
      optimalRange: [70, 98],
    },
    {
      key: "ballSpeed",
      label: "Ball Speed",
      unit: "mph",
      icon: "flash",
      category: "ball",
      color: "#34D399",
      description: "Speed of the serve off the paddle",
      optimalRange: [25, 50],
    },
    {
      key: "placement",
      label: "Placement",
      unit: "/100",
      icon: "locate",
      category: "ball",
      color: "#34D399",
      description: "Accuracy of serve placement in the target zone",
      optimalRange: [65, 95],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/10",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body stability throughout the serve motion",
      optimalRange: [7, 9.8],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/10",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Smoothness and tempo of the serve motion",
      optimalRange: [6.5, 9.5],
    },
  ],
};
