import { SportCategoryConfig } from "./types";

export const tabletennisBackhandConfig: SportCategoryConfig = {
  sportName: "Table Tennis",
  movementName: "Backhand",
  configKey: "tabletennis-backhand",
  overallScoreLabel: "Backhand Score",
  scores: [
    { key: "power", label: "Power", weight: 0.20 },
    { key: "control", label: "Control", weight: 0.15 },
    { key: "timing", label: "Timing", weight: 0.25 },
    { key: "technique", label: "Technique", weight: 0.20 },
    { key: "consistency", label: "Consistency", weight: 0.20 },
  ],
  metrics: [
    {
      key: "batSpeed",
      label: "Bat Speed",
      unit: "m/s",
      icon: "speedometer",
      category: "power",
      color: "#EF4444",
      description: "Peak bat velocity during the backhand stroke",
      optimalRange: [6, 15],
    },
    {
      key: "timingScore",
      label: "Timing",
      unit: "/100",
      icon: "timer",
      category: "timing",
      color: "#A78BFA",
      description: "Precision of contact timing relative to the ball bounce",
      optimalRange: [70, 98],
    },
    {
      key: "batAngle",
      label: "Bat Angle",
      unit: "deg",
      icon: "analytics",
      category: "technique",
      color: "#6C5CE7",
      description: "Bat face angle at contact point for optimal trajectory",
      optimalRange: [30, 70],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/10",
      icon: "ribbon",
      category: "consistency",
      color: "#FBBF24",
      description: "Stroke repeatability across multiple backhand shots",
      optimalRange: [7, 9.8],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/10",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body stability and center of gravity control during the stroke",
      optimalRange: [7, 9.8],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/10",
      icon: "musical-notes",
      category: "timing",
      color: "#A78BFA",
      description: "Tempo consistency and fluidity of the backhand motion",
      optimalRange: [6.5, 9.5],
    },
  ],
};
