import { SportCategoryConfig } from "./types";

export const tabletennisForehandConfig: SportCategoryConfig = {
  sportName: "Table Tennis",
  movementName: "Forehand",
  configKey: "tabletennis-forehand",
  overallScoreLabel: "Forehand Score",
  scores: [
    { key: "power", label: "Power", weight: 0.17 },
    { key: "control", label: "Control", weight: 0.08 },
    { key: "timing", label: "Timing", weight: 0.08 },
    { key: "technique", label: "Technique", weight: 0.50 },
    { key: "consistency", label: "Consistency", weight: 0.17 },
  ],
  metrics: [
    {
      key: "batSpeed",
      label: "Bat Speed",
      unit: "m/s",
      icon: "speedometer",
      category: "power",
      color: "#EF4444",
      description: "Peak bat head velocity during the forehand drive",
      optimalRange: [8, 18],
    },
    {
      key: "wristAction",
      label: "Wrist Action",
      unit: "deg/s",
      icon: "hand-left",
      category: "technique",
      color: "#6C5CE7",
      description: "Wrist snap angular velocity at contact for topspin generation",
      optimalRange: [300, 700],
    },
    {
      key: "spinRate",
      label: "Spin Rate",
      unit: "rpm",
      icon: "sync",
      category: "ball",
      color: "#34D399",
      description: "Estimated ball spin based on bat angle and wrist snap",
      optimalRange: [2000, 5000],
    },
    {
      key: "footworkScore",
      label: "Footwork",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Foot positioning and weight transfer quality during the stroke",
      optimalRange: [65, 95],
    },
    {
      key: "bodyRotation",
      label: "Body Rotation",
      unit: "deg/s",
      icon: "refresh-circle",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Trunk rotation velocity powering the forehand drive",
      optimalRange: [200, 500],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/10",
      icon: "ribbon",
      category: "consistency",
      color: "#FBBF24",
      description: "Repeatability of bat speed and stroke mechanics across frames",
      optimalRange: [7, 9.8],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/10",
      icon: "musical-notes",
      category: "timing",
      color: "#A78BFA",
      description: "Smoothness and tempo consistency of the stroke cycle",
      optimalRange: [6.5, 9.5],
    },
  ],
};
