import { SportCategoryConfig } from "./types";

export const tabletennisLoopConfig: SportCategoryConfig = {
  sportName: "Table Tennis",
  movementName: "Loop",
  configKey: "tabletennis-loop",
  overallScoreLabel: "Loop Score",
  scores: [
    { key: "power", label: "Power", weight: 0.18 },
    { key: "control", label: "Control", weight: 0.14 },
    { key: "timing", label: "Timing", weight: 0.09 },
    { key: "technique", label: "Technique", weight: 0.41 },
    { key: "consistency", label: "Consistency", weight: 0.18 },
  ],
  metrics: [
    {
      key: "batSpeed",
      label: "Bat Speed",
      unit: "m/s",
      icon: "speedometer",
      category: "power",
      color: "#EF4444",
      description: "Peak bat velocity during the upward brushing motion",
      optimalRange: [10, 22],
    },
    {
      key: "bodyRotation",
      label: "Body Rotation",
      unit: "deg/s",
      icon: "refresh-circle",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Trunk rotation speed generating loop power",
      optimalRange: [250, 600],
    },
    {
      key: "spinRate",
      label: "Spin Rate",
      unit: "rpm",
      icon: "sync",
      category: "ball",
      color: "#34D399",
      description: "Heavy topspin rate produced by the loop stroke",
      optimalRange: [3000, 6000],
    },
    {
      key: "contactPoint",
      label: "Contact Point",
      unit: "/100",
      icon: "locate",
      category: "technique",
      color: "#FBBF24",
      description: "Optimal contact point position relative to body and table",
      optimalRange: [65, 95],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body stability and weight transfer during the explosive loop",
      optimalRange: [65, 95],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "timing",
      color: "#A78BFA",
      description: "Tempo consistency of the loop stroke cycle",
      optimalRange: [60, 92],
    },
  ],
};
