import { SportCategoryConfig } from "./types";

export const tabletennisServeConfig: SportCategoryConfig = {
  sportName: "Table Tennis",
  movementName: "Serve",
  configKey: "tabletennis-serve",
  overallScoreLabel: "Serve Score",
  scores: [
    { key: "spin", label: "Spin", weight: 0.25 },
    { key: "technique", label: "Technique", weight: 0.25 },
    { key: "placement", label: "Placement", weight: 0.20 },
    { key: "deception", label: "Deception", weight: 0.15 },
    { key: "consistency", label: "Consistency", weight: 0.15 },
  ],
  metrics: [
    {
      key: "spinVariation",
      label: "Spin Variation",
      unit: "rpm",
      icon: "sync",
      category: "ball",
      color: "#34D399",
      description: "Range of spin types and rates applied across serves",
      optimalRange: [1500, 4500],
    },
    {
      key: "batAngle",
      label: "Bat Angle",
      unit: "deg",
      icon: "analytics",
      category: "technique",
      color: "#6C5CE7",
      description: "Bat face angle at contact determining spin type and direction",
      optimalRange: [20, 65],
    },
    {
      key: "ballSpeed",
      label: "Ball Speed",
      unit: "mph",
      icon: "flash",
      category: "ball",
      color: "#EF4444",
      description: "Speed of the ball after serve contact",
      optimalRange: [15, 40],
    },
    {
      key: "tossHeight",
      label: "Toss Height",
      unit: "cm",
      icon: "arrow-up",
      category: "technique",
      color: "#60A5FA",
      description: "Height of ball toss above the table surface (must be 16cm+ per rules)",
      optimalRange: [16, 30],
    },
    {
      key: "placementScore",
      label: "Placement",
      unit: "/100",
      icon: "locate",
      category: "technique",
      color: "#FBBF24",
      description: "Accuracy of serve placement targeting specific zones",
      optimalRange: [65, 95],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "timing",
      color: "#A78BFA",
      description: "Consistency of serve motion tempo and timing",
      optimalRange: [65, 95],
    },
  ],
};
