import { SportCategoryConfig } from "./types";

export const tennisBackhandConfig: SportCategoryConfig = {
  sportName: "Tennis",
  movementName: "Backhand",
  configKey: "tennis-backhand",
  overallScoreLabel: "Backhand Score",
  scores: [
    { key: "power", label: "Power", weight: 0.20 },
    { key: "control", label: "Control", weight: 0.25 },
    { key: "timing", label: "Timing", weight: 0.25 },
    { key: "technique", label: "Technique", weight: 0.15 },
    { key: "consistency", label: "Consistency", weight: 0.15 },
  ],
  metrics: [
    {
      key: "wristSpeed",
      label: "Wrist Speed",
      unit: "m/s",
      icon: "speedometer",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Peak wrist velocity during the backhand swing",
      optimalRange: [20, 35],
    },
    {
      key: "elbowAngle",
      label: "Elbow Angle",
      unit: "deg",
      icon: "body",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Average elbow angle — tighter for one-handed, wider for two-handed",
      optimalRange: [110, 155],
    },
    {
      key: "shoulderRotation",
      label: "Shoulder Rotation",
      unit: "deg/s",
      icon: "refresh-circle",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Trunk rotation velocity on the backhand side",
      optimalRange: [400, 800],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Weight transfer stability during the backhand stroke",
      optimalRange: [70, 98],
    },
    {
      key: "ballSpeed",
      label: "Ball Speed",
      unit: "mph",
      icon: "flash",
      category: "ball",
      color: "#34D399",
      description: "Estimated ball speed off the backhand",
      optimalRange: [45, 90],
    },
    {
      key: "trajectoryArc",
      label: "Trajectory Arc",
      unit: "deg",
      icon: "trending-up",
      category: "ball",
      color: "#6C5CE7",
      description: "Ball flight arc angle",
      optimalRange: [8, 22],
    },
    {
      key: "spinRate",
      label: "Spin Rate",
      unit: "rpm",
      icon: "sync",
      category: "ball",
      color: "#34D399",
      description: "Estimated spin RPM on the backhand",
      optimalRange: [700, 2500],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/100",
      icon: "ribbon",
      category: "consistency",
      color: "#6C5CE7",
      description: "Stroke repeatability across frames",
      optimalRange: [70, 98],
    },
    {
      key: "backswingDuration",
      label: "Backswing",
      unit: "s",
      icon: "arrow-back-circle",
      category: "timing",
      color: "#60A5FA",
      description: "Preparation phase duration",
      optimalRange: [0.3, 0.8],
    },
    {
      key: "contactTiming",
      label: "Contact Timing",
      unit: "s",
      icon: "locate",
      category: "timing",
      color: "#6C5CE7",
      description: "Contact window duration",
      optimalRange: [0.02, 0.08],
    },
    {
      key: "followThroughDuration",
      label: "Follow-through",
      unit: "s",
      icon: "arrow-forward-circle",
      category: "timing",
      color: "#60A5FA",
      description: "Follow-through phase after ball contact",
      optimalRange: [0.4, 1.0],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Swing rhythm smoothness",
      optimalRange: [65, 95],
    },
    {
      key: "contactHeight",
      label: "Contact Height",
      unit: "m",
      icon: "resize",
      category: "technique",
      color: "#FBBF24",
      description: "Height of contact point above ground",
      optimalRange: [0.80, 1.05],
    },
  ],
};
