import { SportCategoryConfig } from "./types";

export const tennisForehandConfig: SportCategoryConfig = {
  sportName: "Tennis",
  movementName: "Forehand",
  configKey: "tennis-forehand",
  overallScoreLabel: "Forehand Score",
  scores: [
    { key: "power", label: "Power", weight: 0.25 },
    { key: "control", label: "Control", weight: 0.20 },
    { key: "timing", label: "Timing", weight: 0.25 },
    { key: "technique", label: "Technique", weight: 0.15 },
    { key: "consistency", label: "Consistency", weight: 0.15 },
  ],
  metrics: [
    {
      key: "wristSpeed",
      label: "Wrist Speed",
      unit: "m/s",
      icon: "speedometer",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Peak wrist velocity during the swing, measuring racket head acceleration",
      optimalRange: [25, 40],
    },
    {
      key: "elbowAngle",
      label: "Elbow Angle",
      unit: "deg",
      icon: "body",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Average elbow joint angle during the stroke, indicating arm extension",
      optimalRange: [120, 160],
    },
    {
      key: "shoulderRotation",
      label: "Shoulder Rotation",
      unit: "deg/s",
      icon: "refresh-circle",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Angular velocity of torso rotation, measuring trunk rotation power",
      optimalRange: [500, 900],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/100",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Hip-to-ankle alignment stability throughout the stroke",
      optimalRange: [70, 98],
    },
    {
      key: "ballSpeed",
      label: "Ball Speed",
      unit: "mph",
      icon: "flash",
      category: "ball",
      color: "#34D399",
      description: "Estimated ball speed after contact based on trajectory analysis",
      optimalRange: [55, 100],
    },
    {
      key: "trajectoryArc",
      label: "Trajectory Arc",
      unit: "deg",
      icon: "trending-up",
      category: "ball",
      color: "#6C5CE7",
      description: "Curvature of the ball's flight path indicating topspin/flat shot",
      optimalRange: [8, 25],
    },
    {
      key: "spinRate",
      label: "Spin Rate",
      unit: "rpm",
      icon: "sync",
      category: "ball",
      color: "#34D399",
      description: "Estimated ball spin based on trajectory deviations",
      optimalRange: [800, 2800],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/100",
      icon: "ribbon",
      category: "consistency",
      color: "#6C5CE7",
      description: "Variance in elbow angles and wrist speeds across the video",
      optimalRange: [70, 98],
    },
    {
      key: "backswingDuration",
      label: "Backswing",
      unit: "s",
      icon: "arrow-back-circle",
      category: "timing",
      color: "#60A5FA",
      description: "Time spent in the preparation phase before the forward swing",
      optimalRange: [0.3, 0.7],
    },
    {
      key: "contactTiming",
      label: "Contact Timing",
      unit: "s",
      icon: "locate",
      category: "timing",
      color: "#6C5CE7",
      description: "Duration of the contact window, shorter = cleaner strike",
      optimalRange: [0.02, 0.08],
    },
    {
      key: "followThroughDuration",
      label: "Follow-through",
      unit: "s",
      icon: "arrow-forward-circle",
      category: "timing",
      color: "#60A5FA",
      description: "Time spent in the follow-through phase after contact",
      optimalRange: [0.4, 1.0],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/100",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Smoothness of the speed profile throughout the swing",
      optimalRange: [65, 95],
    },
    {
      key: "contactHeight",
      label: "Contact Height",
      unit: "m",
      icon: "resize",
      category: "technique",
      color: "#FBBF24",
      description: "Height of contact point relative to ground",
      optimalRange: [0.85, 1.10],
    },
  ],
};
