import { SportCategoryConfig } from "./types";

export const tennisVolleyConfig: SportCategoryConfig = {
  sportName: "Tennis",
  movementName: "Volley",
  configKey: "tennis-volley",
  overallScoreLabel: "Volley Score",
  scores: [
    { key: "power", label: "Power", weight: 0.10 },
    { key: "control", label: "Control", weight: 0.61 },
    { key: "timing", label: "Timing", weight: 0.08 },
    { key: "technique", label: "Technique", weight: 0.15 },
    { key: "consistency", label: "Consistency", weight: 0.06 },
  ],
  metrics: [
    {
      key: "reactionSpeed",
      label: "Reaction Speed",
      unit: "ms",
      icon: "flash",
      category: "timing",
      color: "#6C5CE7",
      description: "Time from ball approach to racket movement initiation",
      optimalRange: [150, 350],
    },
    {
      key: "racketPrep",
      label: "Racket Prep",
      unit: "/100",
      icon: "hand-right",
      category: "technique",
      color: "#FBBF24",
      description: "How early and compact the racket preparation is",
      optimalRange: [70, 98],
    },
    {
      key: "wristFirmness",
      label: "Wrist Firmness",
      unit: "/100",
      icon: "lock-closed",
      category: "technique",
      color: "#FBBF24",
      description: "Wrist stability at contact — firm wrist is key for volleys",
      optimalRange: [75, 98],
    },
    {
      key: "splitStepTiming",
      label: "Split Step",
      unit: "s",
      icon: "footsteps",
      category: "timing",
      color: "#60A5FA",
      description: "Timing of the split step relative to opponent's contact",
      optimalRange: [0.1, 0.4],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/10",
      icon: "body",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body stability during the volley",
      optimalRange: [7, 9.8],
    },
    {
      key: "contactHeight",
      label: "Contact Height",
      unit: "m",
      icon: "resize",
      category: "technique",
      color: "#FBBF24",
      description: "Height of racket at ball contact",
      optimalRange: [0.8, 1.5],
    },
    {
      key: "stepForward",
      label: "Step Forward",
      unit: "/100",
      icon: "walk",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Quality of forward step into the volley",
      optimalRange: [60, 95],
    },
    {
      key: "ballSpeed",
      label: "Ball Speed",
      unit: "mph",
      icon: "speedometer",
      category: "ball",
      color: "#34D399",
      description: "Ball speed after the volley",
      optimalRange: [30, 70],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/10",
      icon: "ribbon",
      category: "consistency",
      color: "#6C5CE7",
      description: "Repeatability of volley technique",
      optimalRange: [7, 9.8],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/10",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Fluidity and rhythm of the volley motion",
      optimalRange: [6.5, 9.5],
    },
  ],
};
