import { SportCategoryConfig } from "./types";

export const tennisServeConfig: SportCategoryConfig = {
  sportName: "Tennis",
  movementName: "Serve",
  configKey: "tennis-serve",
  overallScoreLabel: "Serve Score",
  scores: [
    { key: "power", label: "Power", weight: 0.30 },
    { key: "control", label: "Control", weight: 0.25 },
    { key: "timing", label: "Timing", weight: 0.20 },
    { key: "technique", label: "Technique", weight: 0.15 },
    { key: "consistency", label: "Consistency", weight: 0.10 },
  ],
  metrics: [
    {
      key: "wristSpeed",
      label: "Wrist Speed",
      unit: "m/s",
      icon: "speedometer",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Peak wrist snap velocity at ball contact",
      optimalRange: [30, 50],
    },
    {
      key: "shoulderRotation",
      label: "Shoulder Rotation",
      unit: "deg/s",
      icon: "refresh-circle",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Trunk rotation velocity during the service motion",
      optimalRange: [600, 1100],
    },
    {
      key: "tossHeight",
      label: "Toss Height",
      unit: "m",
      icon: "arrow-up-circle",
      category: "technique",
      color: "#FBBF24",
      description: "Ball toss height relative to contact point",
      optimalRange: [0.3, 0.8],
    },
    {
      key: "trophyAngle",
      label: "Trophy Position",
      unit: "deg",
      icon: "body",
      category: "technique",
      color: "#FBBF24",
      description: "Elbow angle at the trophy (loaded) position",
      optimalRange: [80, 110],
    },
    {
      key: "pronation",
      label: "Pronation",
      unit: "deg/s",
      icon: "hand-right",
      category: "technique",
      color: "#FBBF24",
      description: "Forearm pronation speed at contact",
      optimalRange: [400, 900],
    },
    {
      key: "ballSpeed",
      label: "Serve Speed",
      unit: "mph",
      icon: "flash",
      category: "ball",
      color: "#34D399",
      description: "Ball speed after the serve",
      optimalRange: [70, 130],
    },
    {
      key: "trajectoryArc",
      label: "Trajectory Arc",
      unit: "deg",
      icon: "trending-up",
      category: "ball",
      color: "#6C5CE7",
      description: "Ball trajectory angle over the net",
      optimalRange: [3, 15],
    },
    {
      key: "spinRate",
      label: "Spin Rate",
      unit: "rpm",
      icon: "sync",
      category: "ball",
      color: "#34D399",
      description: "Spin applied to the serve",
      optimalRange: [1000, 3500],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/10",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body balance throughout the service motion",
      optimalRange: [6.5, 9.5],
    },
    {
      key: "backswingDuration",
      label: "Wind-up",
      unit: "s",
      icon: "arrow-back-circle",
      category: "timing",
      color: "#60A5FA",
      description: "Duration of the wind-up and loading phase",
      optimalRange: [0.8, 1.5],
    },
    {
      key: "contactTiming",
      label: "Contact Timing",
      unit: "s",
      icon: "locate",
      category: "timing",
      color: "#6C5CE7",
      description: "Timing precision at the contact point",
      optimalRange: [0.02, 0.06],
    },
    {
      key: "contactHeight",
      label: "Contact Height",
      unit: "m",
      icon: "resize",
      category: "technique",
      color: "#FBBF24",
      description: "Height of ball at contact, higher = better angle",
      optimalRange: [2.2, 2.8],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/10",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Smoothness and consistency of the service motion",
      optimalRange: [6.5, 9.5],
    },
  ],
};
