import { SportCategoryConfig } from "./types";

export const paddleBackhandConfig: SportCategoryConfig = {
  sportName: "Paddle",
  movementName: "Backhand",
  configKey: "paddle-backhand",
  overallScoreLabel: "Backhand Score",
  scores: [
    { key: "power", label: "Power", weight: 0.20 },
    { key: "control", label: "Control", weight: 0.20 },
    { key: "timing", label: "Timing", weight: 0.20 },
    { key: "technique", label: "Technique", weight: 0.25 },
    { key: "consistency", label: "Consistency", weight: 0.15 },
  ],
  metrics: [
    {
      key: "wristSpeed",
      label: "Wrist Speed",
      unit: "m/s",
      icon: "speedometer",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Peak wrist velocity during the backhand swing",
      optimalRange: [15, 28],
    },
    {
      key: "elbowAngle",
      label: "Elbow Angle",
      unit: "deg",
      icon: "body",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Average elbow joint angle during the backhand stroke",
      optimalRange: [100, 145],
    },
    {
      key: "shoulderRotation",
      label: "Shoulder Rotation",
      unit: "deg/s",
      icon: "refresh-circle",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Angular velocity of torso rotation during the backhand",
      optimalRange: [350, 750],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/10",
      icon: "footsteps",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Body stability throughout the backhand stroke",
      optimalRange: [7, 9.8],
    },
    {
      key: "ballSpeed",
      label: "Ball Speed",
      unit: "mph",
      icon: "flash",
      category: "ball",
      color: "#34D399",
      description: "Estimated ball speed after backhand contact",
      optimalRange: [35, 70],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/10",
      icon: "ribbon",
      category: "consistency",
      color: "#6C5CE7",
      description: "Repeatability of backhand technique across strokes",
      optimalRange: [7, 9.8],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/10",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Fluidity and timing flow of the backhand motion",
      optimalRange: [6.5, 9.5],
    },
    {
      key: "contactHeight",
      label: "Contact Height",
      unit: "m",
      icon: "resize",
      category: "technique",
      color: "#FBBF24",
      description: "Height of paddle at ball contact",
      optimalRange: [0.6, 1.05],
    },
  ],
};
