import { SportCategoryConfig } from "./types";

export const tennisGameConfig: SportCategoryConfig = {
  sportName: "Tennis",
  movementName: "Game",
  configKey: "tennis-game",
  overallScoreLabel: "Game Score",
  scores: [
    { key: "power", label: "Power", weight: 0.21 },
    { key: "control", label: "Control", weight: 0.42 },
    { key: "timing", label: "Timing", weight: 0.08 },
    { key: "technique", label: "Technique", weight: 0.08 },
    { key: "consistency", label: "Consistency", weight: 0.21 },
  ],
  metrics: [
    {
      key: "courtCoverage",
      label: "Court Coverage",
      unit: "/100",
      icon: "move",
      category: "biomechanics",
      color: "#6C5CE7",
      description: "Percentage of court area covered during rallies",
      optimalRange: [60, 95],
    },
    {
      key: "recoverySpeed",
      label: "Recovery Speed",
      unit: "m/s",
      icon: "speedometer",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Speed of recovery to ready position after each shot",
      optimalRange: [2.0, 5.0],
    },
    {
      key: "avgBallSpeed",
      label: "Avg Ball Speed",
      unit: "mph",
      icon: "flash",
      category: "ball",
      color: "#34D399",
      description: "Average ball speed across all shots",
      optimalRange: [50, 90],
    },
    {
      key: "shotVariety",
      label: "Shot Variety",
      unit: "/100",
      icon: "options",
      category: "technique",
      color: "#FBBF24",
      description: "Diversity of shots used during play",
      optimalRange: [50, 90],
    },
    {
      key: "balanceScore",
      label: "Balance",
      unit: "/10",
      icon: "body",
      category: "biomechanics",
      color: "#60A5FA",
      description: "Overall body balance during match play",
      optimalRange: [6.5, 9.5],
    },
    {
      key: "rallyLength",
      label: "Rally Length",
      unit: "shots",
      icon: "repeat",
      category: "consistency",
      color: "#6C5CE7",
      description: "Average number of shots per rally",
      optimalRange: [4, 12],
    },
    {
      key: "shotConsistency",
      label: "Consistency",
      unit: "/10",
      icon: "ribbon",
      category: "consistency",
      color: "#6C5CE7",
      description: "Overall consistency of shot technique",
      optimalRange: [6.5, 9.5],
    },
    {
      key: "rhythmConsistency",
      label: "Rhythm",
      unit: "/10",
      icon: "musical-notes",
      category: "timing",
      color: "#6C5CE7",
      description: "Movement rhythm and pacing between shots",
      optimalRange: [6, 9],
    },
  ],
};
